### ISSUE TITLE
Fallo iluminación de personaje 

### ISSUE THREAD

**Issue by Adelpozo04** [Proyectos1-FDI-UCM/c2223-Grupo04#10]
### Descripción
Al intentar interactuar con un NPC, este se ilumina parcialmente, saliendo una versión en miniatura de él. Lo esperado es que se ilumina entero, no solo una versión pequeña de él.

### Pasos
1.	Acércate a un NPC 
2.	Coloca tu cursor encima de este

### Captura de pantalla o vídeo
![8](https://user-images.githubusercontent.com/125442786/235113578-b62aa188-0763-4ad6-865c-a3a1e81e987e.png)

**Comment by Paigro** [comment]
Es feature
