### ISSUE TITLE
Fallo imposibilidad de quitar piedra pequeña

### ISSUE THREAD

**Issue by Adelpozo04** [Proyectos1-FDI-UCM/c2223-Grupo04#11]
### Descripción
Después de que pasara el tornado por primera vez intente quitar las piedras que había en el campo izquierdo de Giussepe. Al intentar quitar la de abajo a la izquierda esta no me lo permitía. Creo que puede ser porque el tornado a colocado piedritas donde ya había piedritas. Lo ideal es que te deje quitar rocas

### Pasos
1.	No quites ninguna de las piedritas
2.	Deja que pasen varios tornados
3.	Comprueba si alguna de las piedritas tienen un fondo de interacción raro y prueba a quitarla.

### Captura de pantalla o vídeo
![9](https://user-images.githubusercontent.com/125442786/235114596-dab29759-397a-4305-9f1a-7a5f0a9f4ec3.png)

**Comment by PablooMS** [comment]
Este bug también sucede a veces durante el nivel del mono, pero en ese caso no se necesitaba que pasase ningún tornado, simplemente se eliminaban
